### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/IaC-at-home2#10]
- [x] bare metal install of ubuntu for rk1 and rpi4
- [x] Create K3S cluster
- [x] Dashboard
- [ ] Move Installs to M2 SSDS (including rpi4 in some slots using SATA?)
- [ ] Make additional features configurable (via tags?)
- [ ] Longhorn
- [ ] NFS PVC provisioning using NAS
- [ ] My previous apps
  - [ ] ddclient
  - [ ] minecraft servers
  - [ ] add a docker account for better dockerhub quota
- [ ] certificate manager using let's encrypt
- [ ] metallb
- [ ] ingress - use nginx instead of Traefik
- [ ] certificate manager using let's encrypt

**Comment by gilesknap** [comment]
PVC backup with restore during Ansible rebuild.
